--- #YAML:1.0
name:               MooseX-Role-Restricted
version:            1.03
abstract:           ~
author:
    - Graham Barr <gbarr@pobox.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Attribute::Handlers:  0.88
    Moose:                0.90
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
